config/routes.rb
Rails.application.routes.draw do

  resources :categories do

  resources :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true,
    uniqueness: true

    validates :details, presence: true,
    length: { minimum: 5 }

    has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :category  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController 
    before_action :set_category, only: %i[ show edit update destroy ]
    # get '/categories', will show on browser /categories
    def index 
        @categories = Category.all
    end

    # get '/categories/new', will show on browser /categories/new
    def new 
        @category = Category.new
    end

    
    def create
        @category = Category.new(category_params)

        if @category.save 
            # render json: @category.to_json 
            redirect_to categories_path
        else 
            render :new 
        end
    end

    def show
        @category = Category.find(params["id"])
    end

    def edit
  
    end
  
    def update
        respond_to do |format|
            if @category.update(category_params)
              format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
              format.json { render :show, status: :ok, location: @category }
            else
              format.html { render :edit, status: :unprocessable_entity }
              format.json { render json: @category.errors, status: :unprocessable_entity }
            end
          end
    end
  
    def destroy
        @category.destroy

        respond_to do |format|
          format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
          format.json { head :no_content }
        end
    end

    private 
    def set_category
        @category = Category.find(params[:id])
      end

    def category_params 
        params.require(:category).permit(:name, :details)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController  
    before_action :get_category

    def index 
        @tasks = @category.tasks
    end

    def new 
        @task = @category.tasks.build
    end

    def create 
        @task = @category.tasks.build(task_params)
        if @task.save 
            redirect_to category_tasks_path
        else
            render :new
        end
    end

    def show
        @task = Task.find(params["id"])
    end

    def edit
  
    end

    def update
        respond_to do |format|
            if @task.update(task_params)
              format.html { redirect_to task_url(@task), notice: "Task was successfully updated." }
              format.json { render :show, status: :ok, location: @task }
            else
              format.html { render :edit, status: :unprocessable_entity }
              format.json { render json: @task.errors, status: :unprocessable_entity }
            end
          end
    end

    def destroy
        @task.destroy

        respond_to do |format|
          format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
          format.json { head :no_content }
        end
    end



    private

    def get_category
        @category = Category.find(params[:category_id])
    end

    def task_params
        params.require(:task).permit(:name, :description, :deadline)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_category.html.erb
<%# to be rendered in articles/1 or show.html.erb %>

<p>ID: <%= category.id %></p>
<p>Name: <%= category.name %></p>

app/views/categories/_form.html.erb
<%= form_with(model: category, class: 'form-class') do |f| %>

<p>
  <!-- we can access our controller instance variables here -->
  <% if @category.errors.any? %>
    <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</p>

<p>
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
</p>

<p>
    <%= f.label :details %><br/>
    <%= f.text_field :details %>
</p>

<p>
  <button type="button" class="btn btn-primary btn-sm"><%= f.submit class: "bg-transparent shadow-none border-0 text-white"  %></button><br/>
</p>

<% end %>

app/views/categories/edit.html.erb
<nav class="navbar navbar-dark bg-dark position-relative w-100">
  <span class="navbar-brand mb-0 h1">TinyThoughts</span>
</nav>
<div class="p-3 mb-2 bg-secondary text-white vh-100">
<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>
</div>

app/views/categories/index.html.erb
<%# /categories %>
<nav class="navbar navbar-dark bg-dark position-relative w-100">
  <span class="navbar-brand mb-0 h1">TinyThoughts</span>
</nav>
<div class="p-3 mb-2 bg-secondary text-white vh-100">
 <h1>Your Categories</h1>
<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Name</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
      <% @categories.each do |category| %>
    <tr>
       <td>
        <%= category.id %>
      </td>
      <td>
        <%= category.name %>
      </td>
      <td>
        <%= link_to("See category", category_path(category.id))%>
      </td>
    </tr>
<% end %>
  </tbody>
</table>
  <div class="w-100 p-3 d-flex flex-row-reverse">
    <button type="button" class="btn btn-primary btn-sm"><%= link_to "Add new category", new_category_path, :class => "text-decoration-none text-white" %></button>
   </div>
<%= @test %>
</div>

app/views/categories/new.html.erb
<nav class="navbar navbar-dark bg-dark position-relative w-100">
  <span class="navbar-brand mb-0 h1">TinyThoughts</span>
</nav>
<div class="p-3 mb-2 bg-secondary text-white vh-100 d-flex align-items-center justify-content-center">
<div class="card" style="background-color: #212529; width: 15rem;">
<div class="card-body">
 <h5 class="card-title">Make a new Category:</h5>
<%= render "form", category: @category %>

<button type="button" class="btn btn-primary btn-sm"><%= link_to "Go back to categories", categories_path, :class => "text-decoration-none text-white" %></button><br/>
</div>
</div>

app/views/categories/show.html.erb
<!-- let's just display the article's ID in plain text -->
<%# articles/1 %>

<nav class="navbar navbar-dark bg-dark position-relative w-100">
  <span class="navbar-brand mb-0 h1">TinyThoughts</span>
</nav>
<div class="p-3 mb-2 bg-secondary text-white vh-100 d-flex align-items-center justify-content-center">

<div class="card" style="background-color: #212529; width: 15rem;">
<div class="card-body">
    <h5 class="card-title">Category <%= @category.id %></h5>
   <%= render "category", category: @category %> 
  <p>Details: <%= @category.details%></p>
  <div>
  <button type="button" class="btn btn-primary btn-sm"><%= link_to "Edit this category", edit_category_path(@category), :class => "text-decoration-none text-white" %></button><br/><br/>

    <button type="button" class="btn btn-primary btn-sm"><%= link_to "Back to categories", categories_path, :class => "text-decoration-none text-white" %></button><br/><br/>

   <button type="button" class="btn btn-primary btn-sm"><%= link_to "Tasks", category_tasks_path(@category.id), :class => "text-decoration-none text-white" %></button><br/><br/>

  <button type="button" class="btn btn-primary btn-sm"><%= link_to "Destroy this category", @category, method: :delete, :class => "text-decoration-none text-white" %></button><br/><br/>
</div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JournalApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_task.html.erb
<p>Name: <%= task.name %></p>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= form_with model: [@category, @task] do |f| %>

<p>
  <!-- we can access our controller instance variables here -->
  <% if @task.errors.any? %>
    <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</p>

<p>
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
</p>

<p>
    <%= f.label :description %><br/>
    <%= f.text_field :description %>
</p>

<p>
    <%= f.label :deadline %><br/>
    <%= f.text_field :deadline %>
</p>

<p>
  <%= f.submit %>
</p>

<% end %>

<br>

<div>
  <%= link_to "Back to tasks", category_tasks_path %>
</div>

app/views/tasks/index.html.erb
<nav class="navbar navbar-dark bg-dark position-relative w-100">
  <span class="navbar-brand mb-0 h1">TinyThoughts</span>
</nav>
<div class="p-3 mb-2 bg-secondary text-white vh-100">
 <h2>Category #<%= @category.id %> Tasks:</h2>
<table class="table table-dark">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
      <% @tasks.each do |task| %>
    <tr>
       <td>
         <%= task.name %>
      </td>
      <td>
        <%= link_to("See full details of task", category_task_path(@category.id,task.id))%>
      </td>
    </tr>
<% end %>
  </tbody>
</table>
  <div class="w-100 p-3 d-flex flex-row-reverse">
<button type="button" class="btn btn-primary btn-sm"><%= link_to 'Add Task', new_category_task_path(@category), class: "text-decoration-none text-white"%></button><br/><br/> 
</div>
<div class="w-100 p-3 d-flex flex-row-reverse">
<button type="button" class="btn btn-primary btn-sm"><%= link_to "Go to Category", category_path(@category.id), class: "text-decoration-none text-white"%></button><br/><br/>
</div>
</div>

app/views/tasks/new.html.erb
<nav class="navbar navbar-dark bg-dark position-relative w-100">
  <span class="navbar-brand mb-0 h1">TinyThoughts</span>
</nav>
<div class="p-3 mb-2 bg-secondary text-white vh-100 d-flex align-items-center justify-content-center">
<div class="card" style="background-color: #212529; width: 15rem;">
<div class="card-body">

<%= form_with model: [@category, @task] do |f| %>

<p>
  <!-- we can access our controller instance variables here -->
  <% if @task.errors.any? %>
    <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</p>
<h5>Create a task for Category <%= @category.id %></h5>
<p>
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
</p>

<p>
    <%= f.label :description %><br/>
    <%= f.text_field :description %>
</p>

<p>
    <%= f.label :deadline %><br/>
    <%= f.datetime_select :deadline %>
</p>

<p>
  <%= f.submit %>
</p>

<% end %>


<%= link_to "Go back to tasks", category_tasks_path %>
</div>
</div>
</div>

app/views/tasks/show.html.erb
<nav class="navbar navbar-dark bg-dark position-relative w-100">
  <span class="navbar-brand mb-0 h1">TinyThoughts</span>
</nav>
<div class="p-3 mb-2 bg-secondary text-white vh-100 d-flex align-items-center justify-content-center">
<div class="card" style="background-color: #212529; width: 15rem;">
<div class="card-body">
 <h5 class="card-title">Task for Category <%= @category.id %></h5>
<%= render "task", task: @task %> 
<p>Description: <%= @task.description %></p>
<p>Deadline: <%= @task.deadline %></p>

<button type="button" class="btn btn-primary btn-sm"><%= link_to "See category", category_path(@category.id), :class => "text-decoration-none text-white" %></button><br/><br/>

<button type="button" class="btn btn-primary btn-sm"><%= link_to "See all tasks", category_tasks_path(@category.id), :class => "text-decoration-none text-white" %></button><br/><br/>

<button type="button" class="btn btn-primary btn-sm"><%= link_to "Edit this category", edit_category_task_path(@category), :class => "text-decoration-none text-white" %></button><br/><br/>
 </div>
</div>